name: YouTube-Morphe
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Example: 19.47.53'
        required: false
        default: 'Auto'
      DEVICE:
        description: 'Select device'
        required: false
        default: 'arm64-v8a'
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
      CLI:
        description: 'Tool cli'
        required: false
        default: 'MorpheApp/morphe-cli'
      PATCH:
        description: 'Tool patch'
        required: false
        default: 'MorpheApp/morphe-patches'
      FEATURE:
        description: 'Turn on/off feature on: -e "feature", off: -d "feature"'
        required: false
        default: '-d "Custom branding"'
permissions: write-all
env:
    GH_TOKEN: ${{ github.token }}
    VERSION: ${{ inputs.VERSION }}
    DEVICE: ${{ inputs.DEVICE }}
    GITPCLI: ${{ inputs.CLI }}
    GITPATCH: ${{ inputs.PATCH }}
    FEATURE: ${{ inputs.FEATURE }}
jobs:
  build1:
    name: 'Buid Root'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: See build
        run: |
          # kakathic
          [ "$VERSION" ] || VERSION="Auto"
          [ "$DEVICE" ] || DEVICE="arm64-v8a"
          [ "$GITPCLI" ] || GITPCLI="MorpheApp/morphe-cli"
          [ "$GITPATCH" ] || GITPATCH="MorpheApp/morphe-patches"
          [ "$TYPE" ] || TYPE="true"
          [ "$FEATURE" ] || FEATURE='-d "Custom branding"'
          . .github/build.sh
  build2:
    name: 'Buid No-root'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: See build
        run: |
          # kakathic
          sleep 10
          [ "$VERSION" ] || VERSION="Auto"
          [ "$DEVICE" ] || DEVICE="arm64-v8a"
          [ "$GITPCLI" ] || GITPCLI="MorpheApp/morphe-cli"
          [ "$GITPATCH" ] || GITPATCH="MorpheApp/morphe-patches"
          [ "$TYPE" ] || TYPE="false"
          [ "$FEATURE" ] || FEATURE='-d "Custom branding"'
          . .github/build.sh
  build3:
    name: 'Buid Amoled Root'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: See build
        run: |
          # kakathic
          [ "$VERSION" ] || VERSION="Auto"
          [ "$DEVICE" ] || DEVICE="arm64-v8a"
          [ "$GITPCLI" ] || GITPCLI="MorpheApp/morphe-cli"
          [ "$GITPATCH" ] || GITPATCH="MorpheApp/morphe-patches"
          [ "$TYPE" ] || TYPE="true"
          [ "$AMOLED" ] || AMOLED="true"
          [ "$FEATURE" ] || FEATURE='-d "Custom branding"'
          . .github/build.sh
  build4:
    name: 'Buid Amoled No-root'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: See build
        run: |
          # kakathic
          [ "$VERSION" ] || VERSION="Auto"
          [ "$DEVICE" ] || DEVICE="arm64-v8a"
          [ "$GITPCLI" ] || GITPCLI="MorpheApp/morphe-cli"
          [ "$GITPATCH" ] || GITPATCH="MorpheApp/morphe-patches"
          [ "$TYPE" ] || TYPE="false"
          [ "$AMOLED" ] || AMOLED="true"
          [ "$FEATURE" ] || FEATURE='-d "Custom branding"'
          . .github/build.sh

